
require "mbox-dev-native/version"
require "cocoapods"
require "mbox-cocoapods"
require "mbox-dev-native/config.rb"
require "mbox-dev-native/analyzer.rb"
require "mbox-dev-native/podfile.rb"
require "mbox-dev-native/resolver.rb"
require "mbox-dev-native/user_project_integrator.rb"
require "mbox-dev-native/aggregate_target.rb"
require "mbox-dev-native/target_integrator.rb"
require "mbox-dev-native/embed_frameworks_script.rb"
require "mbox-dev-native/remove_dependencies.rb"
require "mbox-dev-native/inject_framework_search_paths.rb"
